![imagen](./img/ejercicios.png)

In [1]:
import numpy as np
import matplotlib.pyplot as plt

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [2]:
my_array = np.arange (0,10)
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
my_array1 = my_array [-1::-2].copy()
print (my_array1)
#my_array1 [::-2] #idem a esto

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [4]:
my_array2 = my_array [-2:-4:-1].copy()
print (my_array2)

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [5]:
my_array3 = my_array [2::-1].copy()
print (my_array3)

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [6]:
my_array4 = np.arange (1,21).reshape (4,5)
print (my_array4)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [7]:
inv1 = np.flip(my_array4, axis = 0)
inv1

array([[16, 17, 18, 19, 20],
       [11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [8]:
inv2 = np.flip(inv1, axis = 1)
inv2 

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [9]:
my_array4b = my_array4[::-1,::-1].copy()
my_array4b

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [10]:
my_array5 = my_array4 [:2,:2].copy() #trabajo con copia, para mantener la original
my_array5

array([[1, 2],
       [6, 7]])

In [11]:
my_array4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [12]:
my_array4 = np.arange (1,21).reshape (4,5)
print (my_array4)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [13]:
my_array6 = my_array4[::2,::2].copy()
my_array6

array([[ 1,  3,  5],
       [11, 13, 15]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [14]:
my_array4 = np.arange (1,21).reshape (4,5)
print (my_array4)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [15]:
my_array7 = my_array4[:3, ::-1].copy()
my_array7

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [16]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
x

array(['Loro', 'Perro', 'Gato', 'Loro', 'Perro'], dtype='<U5')

In [17]:
array18 = x[np.where (x == 'Loro')]
print(array18)

['Loro' 'Loro']


In [18]:
array18b = x [x =='Loro']
print (array18b)

['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [19]:
array10  = np.random.randint(20, size = (2,5,2))
array10

array([[[12,  0],
        [15, 13],
        [15,  9],
        [ 1, 19],
        [11, 18]],

       [[19, 13],
        [ 6, 14],
        [ 5, 18],
        [ 3,  5],
        [ 8,  3]]])

In [20]:
array10b  = np.random.randint(10, size = 20)
array10b

array([5, 6, 1, 3, 3, 6, 4, 3, 7, 1, 4, 0, 9, 6, 6, 7, 1, 7, 1, 0])

In [21]:
array10b = array10b.reshape (2,5,2)
array10b

array([[[5, 6],
        [1, 3],
        [3, 6],
        [4, 3],
        [7, 1]],

       [[4, 0],
        [9, 6],
        [6, 7],
        [1, 7],
        [1, 0]]])

## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [22]:
my_array4 = np.arange (1,21).reshape (4,5)
print (my_array4)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [23]:
my_array10 = my_array4[::-1,::-1].copy() #es identico al ejercicio 4
my_array10

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [24]:
x = np.zeros (10)
print (x)
print("itemsize:", x.itemsize, "bytes")
print("nbytes:", x.nbytes, "bytes")

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
itemsize: 8 bytes
nbytes: 80 bytes


In [25]:
x [3] = 1
print (x)
print("itemsize:", x.itemsize, "bytes")
print("nbytes:", x.nbytes, "bytes")

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
itemsize: 8 bytes
nbytes: 80 bytes


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [26]:
array12 = np.arange (10,50)
array12

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [27]:
array12 =  array12[::-1] #sin copia, modifica el original
array12

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [28]:
import matplotlib.pyplot as plt
def plot_vector_2d(vector2d:np.array, origin:list=[0, 0], **options) -> None:
    return plt.arrow(origin[0], origin[1], vector2d[0], vector2d[1],
              head_width=0.1, head_length=10, length_includes_head=True,
              **options)

In [29]:
u = np.array([10, 0])
v = np.array([49, 0])
#graficamente, se podía representar as'i:

plot_vector2d(v-u, origin=u, color="b", linestyle='dotted')
plot_vector2d(u-v, origin=v+(0,.05), color="r")
plt.axis([0, 60, -1, 2])
plt.text(26, -0.2, "u", color="b", fontsize=18)
plt.text(25, 0.2, "-u", color="r", fontsize=18)
plt.grid()
plt.show()

NameError: name 'plot_vector2d' is not defined

## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [ ]:
array13 = [1,2,0,0,4,0]
array13
#np.__version__

In [ ]:
#la función numpy.flatnonzero deuelve los indices de los elementos no-cero
#de una versión aplanada (matriz de una dimensión) de la matriz a
array13b = np.flatnonzero (array13)
array13b

## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [ ]:
array14  = np.random.randint(500, size = (10,10))
array14

In [ ]:
np.min(array14), np.max(array14)

## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [ ]:
array15  = np.random.random(30)
array15

In [ ]:
array15  = np.random.randint(10, size = 30)
print(array15)
print (f'La media del vector anterior es {np.mean (array15)}')

## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [ ]:
array16  = np.zeros ((7,7)) 
array16

In [ ]:

(f,c) = np.shape(array16)
f1 = np.ones ((1,c))
#print(f1)
c1 = np.ones ((f,1))
#print(c1)

array16 [0,:] = f1 # aquí reemplazo la fila primera 
array16 [-1,:] = f1  #y la última

array16[:, 0] = f1 # esto reemplaza la primera columna
array16 [:,-1] = f1  # y la última

print (array16)

In [ ]:
array16[:,0] #sucede que al hacer el slicing de una columna, sale un vector fila. 
            #Así que basta con sustituirla por la misma matriz fila f1

In [ ]:
def matriz(filas, columnas):
    return [
         [1] * columnas,
         *([1, *([0] * (columnas - 2)), 1] for i in range(filas - 2)),
         [1] * columnas]
matriz (7,7)

## Ejercicio 15
Obtén la siguiente secuencia

```Python
[4., 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2., 1.75, 1.5 ,1.25]
```

In [ ]:
my_array15 = np.arange (4,1, -0.25)
print (my_array15)

## Ejercicio 17
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [ ]:
#con bucles viendo si la posición es par o impar
array17 = np.ones ((8,8), dtype=int)
for i in range(8):
    for j in range(8):
        if (i % 2 == 0 and j % 2 == 0) or (i % 2!= 0 and j % 2!= 0):
            array17[i][j] = 0
array17

In [ ]:
#mediante slicing
array17b = np.zeros((8,8), dtype=int)
array17b [0:8:2, 1:8:2] = 1
array17b [1:8:2, 0:8:2] =1
array17b

In [ ]:
x  = np.ones (64, dtype=int)
#aqui intgentaba manipular los valores según su posición 
array17 = x.reshape (8,8)
array17


## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [ ]:
x = np.array ([[0,1],[1,0]])
y =np.tile (x, 4)
array18 = np.tile (y, (4,1))
array18


## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [ ]:
array19 = np.random.randint (10, size = (5,5))
array19

In [47]:

def  normalizar_array ( arr ): 
    norm_arr = (arr - np. min (arr)) / (np. max (arr) - np. min (arr)) 
    return norm_arr

In [ ]:
normalizar_array (array19)

## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [30]:
array20 = np.arange (0,11)
array20
    

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
array20 [4:8] = -1
array20 

array([ 0,  1,  2,  3, -1, -1, -1, -1,  8,  9, 10])

In [32]:
array20 [4:8] = False
array20 

array([ 0,  1,  2,  3,  0,  0,  0,  0,  8,  9, 10])

## Ejercicio 21
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.