![imagen](./img/ejercicios.png)

## Ejercicio 1
Importa el módulo de `numpy` y obtén su versión.

In [3]:
import numpy as np


In [ ]:
np.__version__


## Ejercicio 2
Crea un array de una dimensión que vaya de 0 a 9. Llamalo `my_array`

In [ ]:
my_array = np.arange(0,10)
my_array


In [ ]:
print(my_array)

## Ejercicio 3
Crea un array 3x3, que sea todo a True

In [11]:
np.full((3,3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Ejercicio 4
Extrae todos los impares de `my_array`

In [38]:
my_array4 = my_array[1::2]

In [ ]:
my_array4

In [ ]:
my_array

## Ejercicio 5
En un nuevo array, sustituye todos los impares de `my_array` por -1

In [ ]:
my_array5 = my_array.copy()
my_array5[my_array % 2 == 1] = -1
my_array5

## Ejercicio 6
En un nuevo array, sustituye todos los impares de `my_array` por -1. Esta vez usa `where`

In [ ]:
my_array6 = np.where(my_array % 2, -1, my_array )
my_array6

## Ejercicio 7
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

In [ ]:
my_array7 = my_array.reshape((2,5))
my_array7

## Ejercicio 8
Concatena los siguientes arrays verticamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [ ]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
# print(a)
# print(b)
my_array8 = np.concatenate ([a,b])
print (my_array8)

## Ejercicio 9
Concatena los siguientes arrays horizontamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [ ]:
#ahora en horizontal, en el eje=1
my_array9 = np.concatenate ([a,b],1)
print (my_array9)

## Ejercicio 10
Encuentra todos los elementos en común entre ambos arrays. [Para ello usa el método `intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

In [10]:
a = np.array([1,2, 3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b,False, False) # No entiendo parametros en True, True

array([2, 4])

## Ejercicio 11
Obtén la documentación acerca de la función `concatenate`

In [ ]:
np.concatenate?

## Ejercicio 12
Crea un array unidimensional que vaya del 0 al 9. Llámalo `my_array`. 
1. Multiplica cada uno de los elementos de `my_array` por 10, en un nuevo array
2. Accede al primer elemento del array
3. Accede al último elemento del array
4. Imprime por pantalla los numeros del 1 al 7

In [ ]:
my_array = np.arange(0,10)
print (my_array)
my_array12 = my_array * 2
print(my_array12)

In [4]:
my_array = np.arange(0,10) #Error que no comprendo
print (my_array)
my_array12b = np.multipy(my_array, 2)
print(my_array12b)

[0 1 2 3 4 5 6 7 8 9]


AttributeError: module 'numpy' has no attribute 'multipy'

## Ejercicio 13
Crea un array manualmente de tres filas por tres columnas. Llámalo `my_matrix`

In [23]:
my_matrix = np.array ([[1,2,3],[5,6,7],[9, 10, 11]])
my_matrix

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [24]:
print("my_matrix ndim: ", my_matrix.ndim)
print("my_matrix shape:", my_matrix.shape)
print("my_matrix size: ", my_matrix.size)

my_matrix ndim:  2
my_matrix shape: (3, 3)
my_matrix size:  9


## Ejercicio 14
Obtén la siguiente secuencia:

```Python
[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
```

In [ ]:
my_array = [1,3]
my_array14 = 

## Ejercicio 15
Obtén la siguiente secuencia

```Python
[4., 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2., 1.75, 1.5 ,1.25]
```

## Ejercicio 16
Lee la imagen "numpy.png"

![imagen](./img/numpy.png)

## Ejercicio 17
Crea un array de 4x1. A continuación convierte el array a un 2x2

In [39]:
x = np.array ([[1],[2],[3],[4]])
print (x)
my_array17 = x.reshape((2,2))
my_array17

[[1]
 [2]
 [3]
 [4]]


array([[1, 2],
       [3, 4]])

## Ejercicio 18
Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes.

In [32]:
import numpy as np
np.random.seed(5)
#aclarar enunciado
array18 = np.random.randint(10, size = (5,3))

In [33]:
array18

array([[3, 6, 6],
       [0, 9, 8],
       [4, 7, 0],
       [0, 7, 1],
       [5, 7, 0]])

## Ejercicio 19
Crea una matriz de 10x1, toda ella compuesta por `False`. Después transformalo en un 2x5

In [38]:
x = np.full((10,1), False, dtype=bool)
my_array19 = x.reshape((2,5))
my_array19


array([[False, False, False, False, False],
       [False, False, False, False, False]])

## Ejercicio 20
Dado el siguiente array

```Python
x =np.random.randint(10, 20, size = (5,2,6))
```

1. ¿Cuántos elementos tiene el array?
2. ¿Cuántas dimensiones?
3. ¿Cuántos elementos tiene cada dimensión?

In [41]:
x =np.random.randint(10, 20, size = (5,2,6))
x

array([[[16, 14, 15, 12, 18, 18],
        [11, 16, 13, 14, 11, 18]],

       [[10, 12, 12, 14, 11, 16],
        [13, 14, 13, 11, 14, 12]],

       [[13, 14, 19, 14, 10, 16],
        [16, 19, 12, 19, 13, 10]],

       [[18, 18, 19, 17, 14, 18],
        [16, 18, 10, 15, 13, 14]],

       [[10, 12, 12, 11, 11, 17],
        [11, 17, 12, 16, 13, 16]]])

In [44]:
print("x ndim: ", x.ndim)
print("x shape:", x.shape)
print("x size: ", x.size)

x ndim:  3
x shape: (5, 2, 6)
x size:  60
