![imagen](./img/ejercicios.png)

## Ejercicio 1
Importa el módulo de `numpy` y obtén su versión.

In [30]:
import numpy as np


In [31]:
np.__version__


'2.1.2'

## Ejercicio 2
Crea un array de una dimensión que vaya de 0 a 9. Llamalo `my_array`

In [32]:
my_array = np.arange(0,10)
my_array


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


## Ejercicio 3
Crea un array 3x3, que sea todo a True

In [34]:
np.full((3,3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Ejercicio 4
Extrae todos los impares de `my_array`

In [35]:
my_array4 = my_array[1::2]

In [36]:
my_array4

array([1, 3, 5, 7, 9])

In [37]:
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Ejercicio 5
En un nuevo array, sustituye todos los impares de `my_array` por -1

In [38]:
my_array5 = my_array.copy()
my_array5[my_array % 2 == 1] = -1
my_array5

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## Ejercicio 6
En un nuevo array, sustituye todos los impares de `my_array` por -1. Esta vez usa `where`

In [39]:
my_array6 = np.where(my_array % 2, -1, my_array )
my_array6

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## Ejercicio 7
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

In [40]:
my_array7 = my_array.reshape((2,5))
my_array7

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Ejercicio 8
Concatena los siguientes arrays verticamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [41]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
# print(a)
# print(b)
my_array8 = np.concatenate ([a,b])
print (my_array8)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## Ejercicio 9
Concatena los siguientes arrays horizontamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [42]:
#ahora en horizontal, en el eje=1
my_array9 = np.concatenate ([a,b],1)
print (my_array9)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


## Ejercicio 10
Encuentra todos los elementos en común entre ambos arrays. [Para ello usa el método `intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

In [43]:
a = np.array([1,2, 3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b, False, False) # No entiendo parametros en True, True.
                            #Juan me explica que la ayuda de la función dice que puede dar valores incoherentes

array([2, 4])

## Ejercicio 11
Obtén la documentación acerca de la función `concatenate`

In [44]:
np.concatenate?

Call signature:  np.concatenate(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <built-in function concatenate>
Docstring:      
concatenate(
    (a1, a2, ...), 
    axis=0, 
    out=None, 
    dtype=None, 
    casting="same_kind"
)

Join a sequence of arrays along an existing axis.

Parameters
----------
a1, a2, ... : sequence of array_like
    The arrays must have the same shape, except in the dimension
    corresponding to `axis` (the first, by default).
axis : int, optional
    The axis along which the arrays will be joined.  If axis is None,
    arrays are flattened before use.  Default is 0.
out : ndarray, optional
    If provided, the destination to place the result. The shape must be
    correct, matching that of what concatenate would have returned if no
    out argument were specified.
dtype : str or dtype
    If provided, the destination array will have this dtype. Cannot be
    provided together with `out`.

    .. versionadded:: 1.20.0

casting 

## Ejercicio 12
Crea un array unidimensional que vaya del 0 al 9. Llámalo `my_array`. 
1. Multiplica cada uno de los elementos de `my_array` por 10, en un nuevo array
2. Accede al primer elemento del array
3. Accede al último elemento del array
4. Imprime por pantalla los numeros del 1 al 7

In [45]:
my_array = np.arange(0,10)
print (my_array)
my_array12 = my_array * 2
print(my_array12)

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]


In [46]:
my_array = np.arange(0,10) 
print (my_array)
my_array12b = np.multiply(my_array, 2)
print(my_array12b)

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]


## Ejercicio 13
Crea un array manualmente de tres filas por tres columnas. Llámalo `my_matrix`

In [47]:
my_matrix = np.array ([[1,2,3],[5,6,7],[9, 10, 11]])
my_matrix

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [48]:
print("my_matrix ndim: ", my_matrix.ndim)
print("my_matrix shape:", my_matrix.shape)
print("my_matrix size: ", my_matrix.size)

my_matrix ndim:  2
my_matrix shape: (3, 3)
my_matrix size:  9


## Ejercicio 14
Obtén la siguiente secuencia:

```Python
[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
```

In [49]:
x = np.arange (1,50,3)
print(x)

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]


In [50]:
x = np.arange (1,50)
x[::3]
print (x[::3])

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]


In [51]:
#mediante bucle que suma un entero al último valor del array
my_array = np.array([1, 4])
while my_array [-1] < 49:
    i = my_array[-1] + 3
    my_array = np.concatenate ((my_array, [i] ))

print (my_array)

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]


## Ejercicio 15
Obtén la siguiente secuencia

```Python
[4., 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2., 1.75, 1.5 ,1.25]
```

In [52]:
my_array15 = np.arange (4,1, -0.25)
print (my_array15)

[4.   3.75 3.5  3.25 3.   2.75 2.5  2.25 2.   1.75 1.5  1.25]


## Ejercicio 16
Lee la imagen "numpy.png"

![imagen](./img/numpy.png)

## Ejercicio 17
Crea un array de 4x1. A continuación convierte el array a un 2x2

In [ ]:
x = np.array ([[1],[2],[3],[4]])
print (x)
array17 = x.reshape((2,2))
array17

## Ejercicio 18
Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes.

In [25]:
import numpy as np
np.random.seed(5)
#aclarar enunciado
array18 = np.random.randint(10, size = (4,5,3))

In [ ]:
array18

## Ejercicio 19
Crea una matriz de 10x1, toda ella compuesta por `False`. Después transformalo en un 2x5

In [ ]:
x = np.full((10,1), False, dtype=bool)
my_array19 = x.reshape((2,5))
my_array19


## Ejercicio 20
Dado el siguiente array

```Python
x =np.random.randint(10, 20, size = (5,2,6))
```

1. ¿Cuántos elementos tiene el array?
2. ¿Cuántas dimensiones?
3. ¿Cuántos elementos tiene cada dimensión?

In [ ]:
x =np.random.randint(10, 20, size = (5,2,6))
x

In [ ]:
print("x ndim: ", x.ndim)
print("x shape:", x.shape)
print("x size: ", x.size)